name: Sync multiple branches
on:
  push:
    branches:
      - 'staging'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
    
      - name: Merge staging -> master
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: staging
          target_branch: master
          github_token: ${{ secrets.ITHUB_TOKEN }}